name: vprscore
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - dm-haiku==0.0.13
    - filelock==3.17.0
    - fsspec==2025.2.0
    - huggingface-hub==0.29.1
    - idna==3.10
    - importlib-metadata==8.6.1
    - jax==0.4.30
    - jax-cuda12-pjrt==0.4.30
    - jax-cuda12-plugin==0.4.30
    - jaxlib==0.4.30
    - jmp==0.0.4
    - joblib==1.4.2
    - ml-dtypes==0.5.1
    - nucleotide-transformer==0.0.1
    - numpy==2.0.2
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvcc-cu12==12.6.85
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.6.0.74
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-nccl-cu12==2.24.3
    - nvidia-nvjitlink-cu12==12.6.85
    - opt-einsum==3.4.0
    - packaging==24.2
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - scipy==1.13.1
    - tabulate==0.9.0
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - urllib3==2.3.0
    - zipp==3.21.0
